//! cofhe wire-format compatibility test: decrypt real cofhe-produced ciphertexts.
//!
//! Locks Teecryptor's decrypt against the real cofhe wire format. The corpus
//! is generated by `tools/ct-export` in **cofhe**, using cofhe's committed
//! dev zone-0 `ClientKey` + `CompactPublicKey` and the canonical
//! `encryption::encrypt_with_public` path (compact=false → pre-expanded form,
//! same as ct-server emits over `/GetCT`). Output is copied verbatim into
//! `tests/cofhe_compat/` (see that dir's README for the procedure).
//!
//! If this test ever fails, **stop and investigate** — either:
//! 1. cofhe's `ClientKey` / params changed (regenerate the corpus), OR
//! 2. Our `safe_deserialize` / decrypt mapping drifted, OR
//! 3. A tfhe-rs version bump rotated the safe-serialize header.
//!
//! This corpus is in the plain (pre-expanded) form, so the test exercises the
//! legacy plain path and is compiled only under `legacy-plain-decrypt`.
#![cfg(feature = "legacy-plain-decrypt")]

use std::fs;
use std::path::{Path, PathBuf};

use primitive_types::U256;
use serde::Deserialize;
use teecryptor::decrypt::{decrypt, EncryptionType};
use teecryptor::keys::KeyStore;
use zeroize::Zeroizing;

#[derive(Deserialize)]
struct ManifestEntry {
    file: String,
    name: String,
    encryption_type: i32,
    compact: bool,
    gzipped: bool,
    security_zone: i32,
    expected_plaintext_hex: String,
}

fn corpus_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/cofhe_compat")
}

fn parse_u256_hex(s: &str) -> U256 {
    let stripped = s.strip_prefix("0x").unwrap_or(s);
    U256::from_str_radix(stripped, 16).expect("valid hex U256")
}

fn load_corpus_key(dir: &Path) -> KeyStore {
    let bytes = fs::read(dir.join("dev_zone0_testkey.bin")).expect(
        "corpus dev_zone0_testkey.bin missing — run `cargo run -p ct-export --release` in \
         cofhe and copy the artifacts into tests/cofhe_compat/ (see README)",
    );
    KeyStore::load(Zeroizing::new(bytes)).expect("load cofhe ClientKey")
}

fn load_manifest(dir: &Path) -> Vec<ManifestEntry> {
    let raw = fs::read_to_string(dir.join("manifest.json"))
        .expect("corpus manifest.json missing — see tests/cofhe_compat/README.md");
    serde_json::from_str(&raw).expect("manifest is valid JSON")
}

#[test]
fn decrypts_real_cofhe_corpus() {
    let dir = corpus_dir();
    let keystore = load_corpus_key(&dir);
    let manifest = load_manifest(&dir);

    assert!(
        !manifest.is_empty(),
        "manifest must contain at least one entry"
    );

    for entry in manifest {
        assert_eq!(
            entry.security_zone, 0,
            "{}: only zone 0 supported in Phase 1",
            entry.name
        );
        assert!(
            !entry.compact && !entry.gzipped,
            "{}: corpus must be in plain (pre-expanded, pre-decompressed) form — \
             that's what ct-server emits over /GetCT",
            entry.name
        );

        let ct_bytes =
            fs::read(dir.join(&entry.file)).unwrap_or_else(|e| panic!("read {}: {e}", entry.file));
        let ty = EncryptionType::from_i32(entry.encryption_type).unwrap_or_else(|_| {
            panic!(
                "{}: unsupported encryption_type {}",
                entry.name, entry.encryption_type
            )
        });
        let client_key = keystore
            .client_key(entry.security_zone)
            .expect("zone-0 key");

        let got = decrypt(client_key, ty, &ct_bytes)
            .unwrap_or_else(|e| panic!("{}: decrypt failed: {e}", entry.name));
        let want = parse_u256_hex(&entry.expected_plaintext_hex);

        assert_eq!(
            got, want,
            "{}: decrypted U256 mismatch — got 0x{:064x}, want {}",
            entry.name, got, entry.expected_plaintext_hex
        );
    }
}
