//! EIP-712 ACP (Access Control Permission) verification, matching cofhe's
//! `ACPIssuerSelf` shape so the same caller wallets/signatures used against
//! the threshold dispatcher work against Teecryptor unchanged.
//!
//! ACP is cofhe's "Permit V3" (cofhe-contracts#87, merged to `v0.2`). It
//! replaces the V2 `Permission` struct: `validatorId`/`validatorContract`
//! become `revokerData`/`revokerContract`, and three scope fields (`scope`,
//! `contracts`, `handles`) are added. **There is no V2 compatibility path** —
//! an upgraded ACL exposes a different `isAllowedWithPermission` selector and
//! a different EIP-712 domain version, so a V2 permit cannot verify against
//! it (and an ACP cannot verify against a pre-upgrade ACL).
//!
//! Phase 2 verification is **delegated to the on-chain TaskManager** via
//! `isAllowedWithPermission(ACP, handle)` — same authority that cofhe's
//! dispatcher consults. Teecryptor does not re-implement ACL semantics
//! locally: it does not evaluate scopes, does not call the revoker contract,
//! and does not check scope/array consistency. It transports the
//! [`AcpData`] from the caller to the contract and trusts the contract's
//! boolean answer (with bounded timeouts on the RPC call). Local-only EIP-712
//! verification is exposed as a helper for tests / future offline modes.
//!
//! Domain (mirrors `EIP712Upgradeable::__EIP712_init_unchained("ACL","2")`):
//!
//! ```text
//! EIP712Domain { name: "ACL", version: "2", chainId, verifyingContract }
//! ```
//!
//! Note the version is **"2"** for ACP (V2 permits used "1"). The upgraded
//! `PermissionedUpgradeable` overrides `_EIP712Name`/`_EIP712Version` so the
//! domain comes from code rather than from storage written at initialization,
//! which is what lets the ACL be upgraded in place without a migration tx.
//!
//! The verifyingContract is the **ACL** contract address per chain, not
//! TaskManager — see the compatibility doc §6 in the gitops repo. chainId comes from the request
//! (`host_chain_id`).

use std::collections::HashMap;
use std::time::Duration;

use alloy::primitives::{Address, Bytes, FixedBytes, U256};
use alloy::providers::{DynProvider, Provider, ProviderBuilder};
use alloy::sol;
use alloy::sol_types::{eip712_domain, SolStruct};
use serde::Deserialize;
use thiserror::Error;

// cofhe's TaskManager + ACL Hardhat artifacts are committed verbatim under
// `abi/`. We load both via `sol!(Name, "path/to/file.json")` — the macro
// reads each artifact's `abi` array and generates the full Rust interface
// (functions, events, errors). This mirrors cofhe dispatcher's
// `threshold-network/crates/dispatcher/src/operations/ct_verifier/mod.rs`,
// and keeps the wire surface a 1:1 copy-paste from cofhe — no hand-curated
// subset to drift over time. See the compatibility doc §7 in the gitops repo
// for the sync procedure.
// Suppress missing-docs on the macro-generated types — the comment block
// above documents what's loaded; per-type comments aren't useful for ABI
// generated code.
#[allow(missing_docs)]
mod abi_loader {
    use alloy::sol;
    sol!(
        #[sol(rpc)]
        #[derive(Debug)]
        ITaskManager,
        "abi/TaskManager.json"
    );
    sol!(
        #[sol(rpc)]
        #[derive(Debug)]
        ACL,
        "abi/ACL.json"
    );
}
pub use abi_loader::{ITaskManager, ACL};

// `ACP` (11-field struct) is generated by the ITaskManager macro from the ABI
// (`internalType: "struct ACP"`) — re-export it under the bare name so the
// rest of this module can just say `ACP`.
use ITaskManager::ACP;

/// Scope discriminator: access to **all** of the issuer's encrypted values.
/// `contracts` and `handles` must be empty.
pub const SCOPE_GLOBAL: u8 = 0;
/// Scope discriminator: access to values readable by any of `contracts`.
pub const SCOPE_CONTRACT: u8 = 1;
/// Scope discriminator: access to the listed ciphertext `handles` only.
pub const SCOPE_HANDLES: u8 = 2;

/// Upper bound on `contracts` / `handles` entries accepted from a caller.
///
/// Purely a bound on the `eth_call` payload we forward — the ACL's scope check
/// is linear in these arrays, and the contract itself sets no limit. Real
/// permissions carry a handful of entries; anything near this cap is either a
/// bug or an attempt to make us pay for a large call.
pub const MAX_SCOPE_ENTRIES: usize = 256;

// EIP-712 typed struct that the issuer actually signs (NOT in the ABI; only
// referenced by Solidity's hand-written `issuerSelfHash` keccak). Must stay
// byte-identical with cofhe's `ACPUtils::issuerSelfHash`:
//
//   keccak256(
//     "ACPIssuerSelf(address issuer,uint64 expiration,address recipient,"
//     "uint256 revokerData,address revokerContract,uint8 scope,"
//     "address[] contracts,bytes32[] handles,bytes32 sealingKey)"
//   )
//
// 9 fields, NO signatures — the signature can't include itself.
//
// The contract hashes the two arrays with `keccak256(abi.encodePacked(...))`.
// For arrays, Solidity's `encodePacked` pads each element to 32 bytes, which
// is exactly EIP-712's array encoding — so alloy's derive agrees with the
// contract without any manual hashing here. `acp_issuer_self_typehash_is_pinned`
// asserts the encoded type string; drift fails at test time.
sol! {
    #[derive(Debug)]
    struct ACPIssuerSelf {
        address issuer;
        uint64 expiration;
        address recipient;
        uint256 revokerData;
        address revokerContract;
        uint8 scope;
        address[] contracts;
        bytes32[] handles;
        bytes32 sealingKey;
    }
}

impl From<&ACP> for ACPIssuerSelf {
    fn from(a: &ACP) -> Self {
        Self {
            issuer: a.issuer,
            expiration: a.expiration,
            recipient: a.recipient,
            revokerData: a.revokerData,
            revokerContract: a.revokerContract,
            scope: a.scope,
            contracts: a.contracts.clone(),
            handles: a.handles.clone(),
            sealingKey: a.sealingKey,
        }
    }
}

/// Hex-serde helper: deserializes a hex string (with or without "0x")
/// into `Vec<u8>`. Mirrors the dispatcher's hex_serde module exactly.
mod hex_serde {
    use serde::{Deserialize, Deserializer, Serialize, Serializer};

    pub fn deserialize<'de, D: Deserializer<'de>>(d: D) -> Result<Vec<u8>, D::Error> {
        let s = String::deserialize(d)?;
        let stripped = s.strip_prefix("0x").unwrap_or(&s);
        if stripped.is_empty() {
            return Ok(vec![]);
        }
        hex::decode(stripped).map_err(serde::de::Error::custom)
    }

    // Kept for serde symmetry (mirrors dispatcher's hex_serde module) and for
    // any future Serialize derive on AcpData. AcpData is currently
    // deserialized only, so this fn is not called in production.
    #[allow(dead_code)]
    pub fn serialize<S: Serializer>(v: &[u8], s: S) -> Result<S::Ok, S::Error> {
        hex::encode(v).serialize(s)
    }
}

/// Serde helper for `revokerData`, which is a `uint256` on-chain.
///
/// Accepts a JSON number **or** a string (decimal, or `0x`-prefixed hex).
/// The default `ACPTimestampRevoker` stores a creation timestamp there —
/// which fits a JSON number — but a custom revoker may use the full `uint256`
/// range, and JSON numbers silently lose precision above 2^53. Callers that
/// need the upper range send a string.
mod u256_flex {
    use alloy::primitives::U256;
    use serde::{Deserialize, Deserializer};

    #[derive(Deserialize)]
    #[serde(untagged)]
    enum NumOrStr {
        Num(u64),
        Str(String),
    }

    pub fn deserialize<'de, D: Deserializer<'de>>(d: D) -> Result<U256, D::Error> {
        match Option::<NumOrStr>::deserialize(d)? {
            None => Ok(U256::ZERO),
            Some(NumOrStr::Num(n)) => Ok(U256::from(n)),
            Some(NumOrStr::Str(s)) => {
                let s = s.trim();
                if s.is_empty() {
                    return Ok(U256::ZERO);
                }
                match s.strip_prefix("0x").or_else(|| s.strip_prefix("0X")) {
                    Some(hex) => U256::from_str_radix(hex, 16).map_err(serde::de::Error::custom),
                    None => U256::from_str_radix(s, 10).map_err(serde::de::Error::custom),
                }
            }
        }
    }
}

/// The ACP fields the caller sends inside `/decrypt`'s JSON body under the
/// `acp` key. Field names and serde shape match the cofhe wire format exactly
/// (camelCase, hex-encoded byte fields) so the same caller wallets/signatures
/// used against the threshold dispatcher work against Teecryptor unchanged.
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AcpData {
    /// EOA that issued the permission (the data owner).
    pub issuer: String,
    /// Unix-seconds expiration; the contract rejects if `< block.timestamp`.
    pub expiration: u64,
    /// Optional secondary recipient (for shared permissions). Use `0x0` if unused.
    pub recipient: String,
    /// Opaque `uint256` handed to `revokerContract` to check revocation. The
    /// default `ACPTimestampRevoker` interprets it as the creation timestamp.
    /// `0` disables the revocation check.
    #[serde(default, deserialize_with = "u256_flex::deserialize")]
    pub revoker_data: U256,
    /// Contract the **ACL** queries to decide whether this permission was
    /// revoked: `withPermission` calls
    /// `IPermissionCustomIdValidator(revokerContract).disabled(issuer, revokerData)`
    /// and reverts `PermissionInvalid_Disabled` when it returns `true` — but
    /// only when this *and* `revoker_data` are both non-zero.
    ///
    /// Teecryptor never calls the revoker itself. It forwards the field so the
    /// issuer signature still verifies and lets the `isAllowedWithPermission`
    /// eth_call perform the check, which is why ACP verification is done fresh
    /// per request and never cached — a cached allow would outlive a revocation.
    /// Use `0x0` to disable the revocation check.
    #[serde(default)]
    pub revoker_contract: String,
    /// Which access mode this permission grants — one of [`SCOPE_GLOBAL`],
    /// [`SCOPE_CONTRACT`], [`SCOPE_HANDLES`]. Defaults to global.
    #[serde(default)]
    pub scope: u8,
    /// Contracts whose readable values this permission covers ([`SCOPE_CONTRACT`]).
    #[serde(default)]
    pub contracts: Vec<String>,
    /// Ciphertext handles this permission covers ([`SCOPE_HANDLES`]).
    #[serde(default)]
    pub handles: Vec<String>,
    /// Sealing key used by sealoutput to re-encrypt output to the issuer.
    #[serde(default)]
    pub sealing_key: String,
    /// `signTypedData` signature by `issuer` over the EIP-712 hash (hex bytes).
    #[serde(with = "hex_serde")]
    pub issuer_signature: Vec<u8>,
    /// Recipient signature (shared permissions only). Empty for self-issued.
    #[serde(default, with = "hex_serde")]
    pub recipient_signature: Vec<u8>,
}

/// Errors from ACP handling. The HTTP layer maps each to a stable
/// `error` code + status; nothing internal is leaked to callers.
#[derive(Debug, Error)]
pub enum AcpError {
    /// One of the ACP's fields could not be parsed (bad hex, bad address, etc).
    #[error("acp malformed: {0}")]
    Malformed(String),
    /// The TaskManager contract returned `false` for `isAllowedWithPermission`.
    #[error("acp denied by ACL")]
    Denied,
    /// The expiration in the ACP is in the past.
    #[error("acp expired")]
    Expired,
    /// The EIP-712 signature recovered to an address other than `issuer`.
    #[error("acp signature does not match issuer")]
    BadSignature,
    /// The request's `host_chain_id` is not in this deployment's configured
    /// chains map. The operator either misspelled a chain id in
    /// `PERMIT_CHAINS_JSON` or this deployment intentionally doesn't serve
    /// that chain.
    #[error("unknown host_chain_id: {0}")]
    UnknownChain(u64),
    /// The verifier is not configured (missing RPC URL or TaskManager address).
    #[error("acp verifier not configured: {0}")]
    Misconfigured(String),
    /// The RPC call to TaskManager exceeded its timeout.
    #[error("acp verifier timed out after {0:?}")]
    Timeout(Duration),
    /// Any other failure on the RPC path (transport, contract decode, etc).
    #[error("acp verifier transport error: {0}")]
    Transport(String),
}

/// Parse an address field. Empty / "0x" become the zero address (cofhe's wire
/// convention for "unused"), so a caller can omit an optional address entirely.
fn parse_addr(label: &str, s: &str) -> Result<Address, AcpError> {
    let stripped = s.strip_prefix("0x").unwrap_or(s);
    if stripped.is_empty() {
        return Ok(Address::ZERO);
    }
    s.parse::<Address>()
        .map_err(|e| AcpError::Malformed(format!("{label} address: {e}")))
}

/// Parse a `bytes32` field. Empty / "0x" / "0" become the all-zero value
/// (cofhe's wire convention); shorter hex is left-padded, which recovers the
/// exact `bytes32` the caller signed over since the type is fixed-width.
fn parse_b32(label: &str, s: &str) -> Result<FixedBytes<32>, AcpError> {
    let stripped = s.strip_prefix("0x").unwrap_or(s);
    if stripped.is_empty() || stripped == "0" {
        return Ok(FixedBytes::ZERO);
    }
    if stripped.len() > 64 {
        return Err(AcpError::Malformed(format!(
            "{label}: expected at most 32 bytes, got {} hex chars",
            stripped.len()
        )));
    }
    let padded = format!("{stripped:0>64}");
    let bytes =
        hex::decode(&padded).map_err(|e| AcpError::Malformed(format!("{label} hex: {e}")))?;
    Ok(FixedBytes::from_slice(&bytes))
}

/// Wire JSON ([`AcpData`], all-strings) → the ABI tuple the contract takes.
/// Parsing only: every field is carried through exactly as the issuer signed
/// it, since any normalization that changed a byte would invalidate the
/// signature the ACL checks.
impl TryFrom<&AcpData> for ACP {
    type Error = AcpError;

    fn try_from(p: &AcpData) -> Result<Self, Self::Error> {
        // Bound the scope arrays before doing any per-element work — this is
        // the only thing standing between a caller and an arbitrarily large
        // eth_call payload.
        if p.contracts.len() > MAX_SCOPE_ENTRIES {
            return Err(AcpError::Malformed(format!(
                "contracts: {} entries exceeds limit of {MAX_SCOPE_ENTRIES}",
                p.contracts.len()
            )));
        }
        if p.handles.len() > MAX_SCOPE_ENTRIES {
            return Err(AcpError::Malformed(format!(
                "handles: {} entries exceeds limit of {MAX_SCOPE_ENTRIES}",
                p.handles.len()
            )));
        }

        let contracts = p
            .contracts
            .iter()
            .enumerate()
            .map(|(i, s)| parse_addr(&format!("contracts[{i}]"), s))
            .collect::<Result<Vec<_>, _>>()?;
        let handles = p
            .handles
            .iter()
            .enumerate()
            .map(|(i, s)| parse_b32(&format!("handles[{i}]"), s))
            .collect::<Result<Vec<_>, _>>()?;

        Ok(ACP {
            issuer: parse_addr("issuer", &p.issuer)?,
            expiration: p.expiration,
            recipient: parse_addr("recipient", &p.recipient)?,
            revokerData: p.revoker_data,
            revokerContract: parse_addr("revokerContract", &p.revoker_contract)?,
            scope: p.scope,
            contracts,
            handles,
            sealingKey: parse_b32("sealingKey", &p.sealing_key)?,
            issuerSignature: Bytes::from(p.issuer_signature.clone()),
            recipientSignature: Bytes::from(p.recipient_signature.clone()),
        })
    }
}

/// Verifier knobs for a single chain. Mirrors cofhe dispatcher's
/// `ChainVerifierConfig` (in `threshold-network/crates/dispatcher/src/config.rs`).
///
/// The alloy `provider` is built **once** at construction (see [`ChainConfig::new`])
/// and reused for every verify call — cloning it is a cheap `Arc` bump that shares
/// the underlying connection pool. Building a fresh provider per call (the old
/// behavior) meant a fresh empty pool → cold DNS+TLS on every request, which
/// intermittently blew the `timeout`. This is the teecryptor analogue of cofhe
/// dispatcher's `get_or_create_provider`; teecryptor's chains are known at boot
/// and immutable, so no lazy `RwLock<HashMap>` cache is needed.
#[derive(Debug, Clone)]
pub struct ChainConfig {
    /// JSON-RPC endpoint for this chain.
    pub rpc_url: String,
    /// Deployed TaskManager contract address on this chain.
    pub task_manager: Address,
    /// Bound the RPC round-trip; matches the `tee-restart-policy=Never` ethos —
    /// a slow RPC must not wedge `/decrypt`.
    pub timeout: Duration,
    /// Pre-built, connection-pooling alloy provider for `rpc_url`. Built once in
    /// [`ChainConfig::new`]; the verify fns clone it (cheap `Arc`) so they reuse
    /// the warm pool instead of opening a cold connection per call.
    provider: DynProvider,
}

impl ChainConfig {
    /// Build a per-chain config, constructing the pooled alloy provider once so
    /// it can be reused across requests. Parsing `rpc_url` here means a bad URL
    /// fails fast at boot instead of on the first `/decrypt`.
    pub fn new(
        rpc_url: String,
        task_manager: Address,
        timeout: Duration,
    ) -> Result<Self, AcpError> {
        let url = rpc_url
            .parse()
            .map_err(|e| AcpError::Misconfigured(format!("rpc_url parse: {e}")))?;
        let provider = ProviderBuilder::new().connect_http(url).erased();
        Ok(Self {
            rpc_url,
            task_manager,
            timeout,
            provider,
        })
    }

    /// Is this chain's RPC answering? `true` only if `eth_blockNumber` returns
    /// within the configured timeout.
    ///
    /// `eth_blockNumber` on purpose: it is the cheapest call that proves the
    /// node is both reachable AND synced enough to answer, and it touches no
    /// contract, so a probe cannot fail for a reason that has nothing to do
    /// with reachability.
    pub async fn probe(&self) -> bool {
        use alloy::providers::Provider as _;
        matches!(
            tokio::time::timeout(self.timeout, self.provider.get_block_number()).await,
            Ok(Ok(_))
        )
    }
}

/// Top-level verifier config — one [`ChainConfig`] per supported chain,
/// keyed by `host_chain_id`. Held inside [`AppState`](crate::http::AppState);
/// built once at boot. Mirrors cofhe dispatcher's `CtVerifierConfig.chains`.
///
/// **Single ABI invariant** (inherited from cofhe): all chains share the
/// same TaskManager ABI. The `sol!` interface declared above is the only
/// one used; if cofhe ever forks the TaskManager interface across chains,
/// this code stops being correct.
///
/// **Cross-chain ACL trust** (worth flagging): the caller's `host_chain_id`
/// selects which chain's ACL contract is consulted. If chain A's ACL grants
/// for the same `handle` differ from chain B's, a caller can pick the looser
/// chain. Teecryptor inherits the dispatcher's implicit assumption that ACL
/// grants are kept consistent across chains by the operator. There is no
/// in-code enforcement.
#[derive(Debug, Clone)]
pub struct ChainsVerifierConfig {
    /// Per-chain configs keyed by `host_chain_id` (the value the caller sends
    /// in the request body and which the EIP-712 domain binds against).
    pub chains: HashMap<u64, ChainConfig>,
}

impl ChainsVerifierConfig {
    /// Build an empty config — equivalent to "no verifier installed". Used
    /// internally when neither `PERMIT_CHAINS_JSON` nor the legacy single-chain
    /// env vars are set.
    pub fn empty() -> Self {
        Self {
            chains: HashMap::new(),
        }
    }

    /// Look up the per-chain config; `None` if this deployment doesn't serve
    /// the chain.
    pub fn get(&self, chain_id: u64) -> Option<&ChainConfig> {
        self.chains.get(&chain_id)
    }

    /// Number of chains configured.
    pub fn len(&self) -> usize {
        self.chains.len()
    }

    /// True iff no chains are configured (treat as "no verifier installed").
    pub fn is_empty(&self) -> bool {
        self.chains.is_empty()
    }
}

/// Verify an ACP by delegating to `TaskManager.isAllowedWithPermission` on
/// the chain identified by `host_chain_id`. Mirrors cofhe dispatcher's
/// `verify_acl`: same contract, same function, same ACP ABI; only the
/// (RPC URL, TaskManager address) pair changes per chain.
///
/// Scope evaluation ([`SCOPE_GLOBAL`] / [`SCOPE_CONTRACT`] / [`SCOPE_HANDLES`])
/// and revocation happen **inside the ACL** — we forward the struct as signed
/// and take the boolean answer.
///
/// **Provider reuse**: the alloy provider is built once at [`ChainConfig::new`]
/// and cloned here (a cheap `Arc` bump) so the warm connection pool is reused
/// across requests — no cold DNS+TLS per call. Mirrors cofhe dispatcher's
/// `get_or_create_provider`.
pub async fn verify_via_taskmanager(
    chains: &ChainsVerifierConfig,
    acp: &AcpData,
    handle: U256,
    host_chain_id: u64,
) -> Result<(), AcpError> {
    let chain_cfg = chains
        .get(host_chain_id)
        .ok_or(AcpError::UnknownChain(host_chain_id))?;

    let permission = ACP::try_from(acp)?;

    let contract = ITaskManager::new(chain_cfg.task_manager, chain_cfg.provider.clone());

    let call = contract.isAllowedWithPermission(permission, handle);
    let fut = call.call();
    let result = tokio::time::timeout(chain_cfg.timeout, fut)
        .await
        .map_err(|_| AcpError::Timeout(chain_cfg.timeout))?;

    match result {
        Ok(true) => Ok(()),
        Ok(false) => Err(AcpError::Denied),
        Err(e) => Err(map_contract_error(e)),
    }
}

/// Verify a *public* (no-ACP) decrypt by delegating to
/// `TaskManager.isPubliclyAllowed(handle)` on the chain identified by
/// `host_chain_id`. Mirrors cofhe dispatcher's `verify_publicly_allowed`
/// (`ct_verifier/mod.rs`): same contract, single-arg call, no `ACP`.
///
/// This is the no-ACP branch of ACL enforcement — a handle the issuer
/// marked publicly decryptable returns `true`. Only consulted when ACL
/// enforcement is ON (i.e. `AppState` was built `with_acp_verifier`); when
/// off, the contract is never reached (it may be unreachable in that
/// deployment).
pub async fn verify_publicly_allowed(
    chains: &ChainsVerifierConfig,
    handle: U256,
    host_chain_id: u64,
) -> Result<(), AcpError> {
    let chain_cfg = chains
        .get(host_chain_id)
        .ok_or(AcpError::UnknownChain(host_chain_id))?;

    let contract = ITaskManager::new(chain_cfg.task_manager, chain_cfg.provider.clone());

    let call = contract.isPubliclyAllowed(handle);
    let fut = call.call();
    let result = tokio::time::timeout(chain_cfg.timeout, fut)
        .await
        .map_err(|_| AcpError::Timeout(chain_cfg.timeout))?;

    match result {
        Ok(true) => Ok(()),
        Ok(false) => Err(AcpError::Denied),
        Err(e) => Err(map_contract_error(e)),
    }
}

/// Map an alloy contract-call error to the most-specific [`AcpError`] we
/// can. The contract reverts with typed errors (the `PermissionInvalid_*`
/// family on ACL, plus various TaskManager errors) on cryptographic /
/// EIP-712 / expiration failures — those are caller-fixable and must map to
/// 401, not 502. Anything we can't decode is treated as transport / infra
/// (502).
///
/// Errors are decoded against the full ABI interfaces (`ACLErrors`,
/// `ITaskManagerErrors`) loaded from the JSONs in `abi/`. The decoded enum
/// only includes the variants we explicitly handle here — every unhandled
/// `ACLErrors::*` or `ITaskManagerErrors::*` variant falls through to the
/// catch-all `Transport`.
///
/// Mirrors cofhe dispatcher's `verify_acl` error handling in
/// `threshold-network/crates/dispatcher/src/operations/ct_verifier/mod.rs`.
fn map_contract_error(e: alloy::contract::Error) -> AcpError {
    // ACL is checked first because the `withPermission` modifier (and the
    // PermissionInvalid_* family it raises) lives on ACL, not TaskManager.
    if let Some(decoded) = e.as_decoded_interface_error::<ACL::ACLErrors>() {
        return match decoded {
            ACL::ACLErrors::PermissionInvalid_Expired(_) => AcpError::Expired,
            ACL::ACLErrors::PermissionInvalid_IssuerSignature(_)
            | ACL::ACLErrors::PermissionInvalid_RecipientSignature(_) => AcpError::BadSignature,
            ACL::ACLErrors::PermissionInvalid_Disabled(_) => AcpError::Denied,
            // SenderNotAllowed, AlreadyDelegated, DirectAllowForbidden,
            // SenderCannotBeDelegateeAddress aren't reachable on this call
            // path (we don't go through the delegation flows) — fall through
            // to Transport so they're at least surfaced in logs.
            _ => AcpError::Transport(format!("ACL revert: {decoded:?}")),
        };
    }
    if let Some(decoded) = e.as_decoded_interface_error::<ITaskManager::ITaskManagerErrors>() {
        // TaskManager-level reverts shouldn't happen on the view-only
        // isAllowedWithPermission path, but if they do, surface them.
        return AcpError::Transport(format!("TaskManager revert: {decoded:?}"));
    }
    AcpError::Transport(e.to_string())
}

/// Local-only EIP-712 verification (no RPC). Useful for tests and for any
/// future offline / pre-flight mode. Does **not** check ACL scope or
/// revocation — only expiration + EIP-712 signature recovery + signer ==
/// issuer.
pub fn verify_local(
    acp: &AcpData,
    chain_id: u64,
    verifying_contract: Address,
    now_unix: u64,
) -> Result<(), AcpError> {
    if acp.expiration < now_unix {
        return Err(AcpError::Expired);
    }
    let permission = ACP::try_from(acp)?;

    let domain = eip712_domain! {
        name: "ACL",
        version: "2",
        chain_id: chain_id,
        verifying_contract: verifying_contract,
    };
    let signed_payload: ACPIssuerSelf = (&permission).into();
    let digest = signed_payload.eip712_signing_hash(&domain);

    let sig_bytes = permission.issuerSignature.as_ref();
    let sig = alloy::primitives::Signature::try_from(sig_bytes)
        .map_err(|e| AcpError::Malformed(format!("issuerSignature: {e}")))?;
    let recovered = sig
        .recover_address_from_prehash(&digest)
        .map_err(|_| AcpError::BadSignature)?;

    if recovered != permission.issuer {
        return Err(AcpError::BadSignature);
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloy::primitives::address;
    use alloy::signers::local::PrivateKeySigner;
    use alloy::signers::SignerSync;

    /// Fixed throwaway test key, used only by these tests. It is deterministic so
    /// the test fixtures stay stable.
    const TEST_PRIV_KEY: &str =
        "0x0000000000000000000000000000000000000000000000000000000000000001";

    /// EIP-712 verifyingContract used in all tests. Arbitrary but consistent.
    const TEST_TM_ADDR: Address = address!("00000000000000000000000000000000000000aa");
    const TEST_CHAIN_ID: u64 = 420105;

    /// Build a self-issued ACP (recipient = 0x0) signed by `signer`, valid
    /// through `expiration`, with the given scope fields. Returns the
    /// wire-shape `AcpData`.
    fn signed_self_acp(
        signer: &PrivateKeySigner,
        expiration: u64,
        scope: u8,
        contracts: Vec<Address>,
        handles: Vec<FixedBytes<32>>,
    ) -> AcpData {
        let issuer = signer.address();
        let signed_payload = ACPIssuerSelf {
            issuer,
            expiration,
            recipient: Address::ZERO,
            revokerData: U256::ZERO,
            revokerContract: Address::ZERO,
            scope,
            contracts: contracts.clone(),
            handles: handles.clone(),
            sealingKey: FixedBytes::ZERO,
        };
        let domain = eip712_domain! {
            name: "ACL",
            version: "2",
            chain_id: TEST_CHAIN_ID,
            verifying_contract: TEST_TM_ADDR,
        };
        let hash = signed_payload.eip712_signing_hash(&domain);
        let sig = signer.sign_hash_sync(&hash).expect("sign");
        AcpData {
            issuer: format!("{issuer:#x}"),
            expiration,
            recipient: format!("{:#x}", Address::ZERO),
            revoker_data: U256::ZERO,
            revoker_contract: format!("{:#x}", Address::ZERO),
            scope,
            contracts: contracts.iter().map(|a| format!("{a:#x}")).collect(),
            handles: handles.iter().map(|h| format!("{h:#x}")).collect(),
            sealing_key: String::new(),
            issuer_signature: sig.as_bytes().to_vec(),
            recipient_signature: vec![],
        }
    }

    /// The common case: global scope, no scope arrays.
    fn signed_global_acp(signer: &PrivateKeySigner, expiration: u64) -> AcpData {
        signed_self_acp(signer, expiration, SCOPE_GLOBAL, vec![], vec![])
    }

    fn signer() -> PrivateKeySigner {
        TEST_PRIV_KEY.parse().expect("test signer")
    }

    /// The single most breakable coupling in this file: the EIP-712 type
    /// string must stay byte-identical with `ACPUtils::issuerSelfHash` in
    /// cofhe-contracts' Permissioned.sol. Reordering or renaming a field here
    /// silently makes every signature recover to the wrong address; this test
    /// turns that into a test failure instead.
    #[test]
    fn acp_issuer_self_typehash_is_pinned() {
        // `\` + newline in a Rust string literal swallows the newline and the
        // next line's indentation, so this is one contiguous string.
        assert_eq!(
            ACPIssuerSelf::eip712_encode_type(),
            "ACPIssuerSelf(address issuer,uint64 expiration,address recipient,\
             uint256 revokerData,address revokerContract,uint8 scope,\
             address[] contracts,bytes32[] handles,bytes32 sealingKey)"
        );
    }

    #[test]
    fn acp_data_deserializes_wire_shape() {
        let json = serde_json::json!({
            "issuer":             "0x0000000000000000000000000000000000000001",
            "expiration":         9999999999u64,
            "issuerSignature":    "deadbeef",
            "recipient":          "0x0000000000000000000000000000000000000002",
            "recipientSignature": "",
            "sealingKey":         "0x",
            "revokerData":        1754700000u64,
            "revokerContract":    "0x0000000000000000000000000000000000000003",
            "scope":              2,
            "contracts":          [],
            "handles":            ["0x00000000000000000000000000000000000000000000000000000000000000ff"]
        });
        let acp: AcpData = serde_json::from_value(json).expect("should parse acp wire shape");
        assert_eq!(acp.issuer_signature, vec![0xde, 0xad, 0xbe, 0xef]);
        assert_eq!(acp.recipient_signature, Vec::<u8>::new());
        assert_eq!(acp.scope, SCOPE_HANDLES);
        assert_eq!(acp.revoker_data, U256::from(1754700000u64));
        assert_eq!(acp.issuer, "0x0000000000000000000000000000000000000001");

        let on_chain = ACP::try_from(&acp).expect("convert");
        assert_eq!(on_chain.handles.len(), 1);
        assert_eq!(on_chain.handles[0], FixedBytes::<32>::from(U256::from(255)));
    }

    /// The scope fields are optional on the wire; omitting them yields a
    /// global-scope ACP with empty arrays and no revoker.
    #[test]
    fn acp_scope_fields_default_when_absent() {
        let json = serde_json::json!({
            "issuer":          "0x0000000000000000000000000000000000000001",
            "expiration":      9999999999u64,
            "recipient":       "0x0000000000000000000000000000000000000000",
            "issuerSignature": "deadbeef"
        });
        let acp: AcpData = serde_json::from_value(json).expect("parse minimal acp");
        assert_eq!(acp.scope, SCOPE_GLOBAL);
        assert!(acp.contracts.is_empty());
        assert!(acp.handles.is_empty());
        assert_eq!(acp.revoker_data, U256::ZERO);

        let on_chain = ACP::try_from(&acp).expect("convert");
        assert_eq!(on_chain.revokerContract, Address::ZERO);
    }

    /// `revokerData` is a uint256 on-chain; a JSON number can't carry the top
    /// of that range, so a string (decimal or hex) must work too.
    #[test]
    fn revoker_data_accepts_number_decimal_and_hex() {
        let parse = |v: serde_json::Value| -> U256 {
            let json = serde_json::json!({
                "issuer":          "0x0000000000000000000000000000000000000001",
                "expiration":      1u64,
                "recipient":       "0x0000000000000000000000000000000000000000",
                "revokerData":     v,
                "issuerSignature": "00"
            });
            serde_json::from_value::<AcpData>(json)
                .expect("parse")
                .revoker_data
        };
        assert_eq!(
            parse(serde_json::json!(1754700000u64)),
            U256::from(1754700000u64)
        );
        assert_eq!(
            parse(serde_json::json!("1754700000")),
            U256::from(1754700000u64)
        );
        assert_eq!(parse(serde_json::json!("0xff")), U256::from(255));
        // Beyond 2^53 — the reason strings are accepted at all.
        let big = "115792089237316195423570985008687907853269984665640564039457584007913129639935";
        assert_eq!(parse(serde_json::json!(big)), U256::MAX);
    }

    #[test]
    fn valid_self_acp_verifies_locally() {
        let s = signer();
        let acp = signed_global_acp(&s, u64::MAX);
        verify_local(&acp, TEST_CHAIN_ID, TEST_TM_ADDR, 0).expect("verify");
    }

    /// Exercises the array members of the typed struct — `SCOPE_HANDLES` with a
    /// populated `handles` array, and `SCOPE_CONTRACT` with `contracts`. If
    /// alloy's array encoding disagreed with the contract's
    /// `keccak256(abi.encodePacked(...))`, a global-scope-only test would never
    /// notice.
    #[test]
    fn scoped_acp_with_arrays_verifies_locally() {
        let s = signer();
        let handles = vec![
            FixedBytes::<32>::from(U256::from(1)),
            FixedBytes::<32>::from(U256::from(0xdead_beefu64)),
        ];
        let acp = signed_self_acp(&s, u64::MAX, SCOPE_HANDLES, vec![], handles);
        verify_local(&acp, TEST_CHAIN_ID, TEST_TM_ADDR, 0).expect("verify scoped");

        let contracts = vec![
            address!("00000000000000000000000000000000000000b1"),
            address!("00000000000000000000000000000000000000b2"),
        ];
        let acp = signed_self_acp(&s, u64::MAX, SCOPE_CONTRACT, contracts, vec![]);
        verify_local(&acp, TEST_CHAIN_ID, TEST_TM_ADDR, 0).expect("verify contract-scoped");
    }

    /// Mutating a scope array must invalidate the signature — this is what
    /// stops a caller widening a scoped permission in transit.
    #[test]
    fn tampering_with_scope_array_rejected() {
        let s = signer();
        let handles = vec![FixedBytes::<32>::from(U256::from(1))];
        let mut acp = signed_self_acp(&s, u64::MAX, SCOPE_HANDLES, vec![], handles);
        acp.handles
            .push(format!("{:#x}", FixedBytes::<32>::from(U256::from(2))));
        let err = verify_local(&acp, TEST_CHAIN_ID, TEST_TM_ADDR, 0).unwrap_err();
        assert!(matches!(err, AcpError::BadSignature), "got {err:?}");
    }

    /// Likewise for the scope discriminator itself.
    #[test]
    fn tampering_with_scope_discriminator_rejected() {
        let s = signer();
        let mut acp = signed_global_acp(&s, u64::MAX);
        acp.scope = SCOPE_CONTRACT;
        let err = verify_local(&acp, TEST_CHAIN_ID, TEST_TM_ADDR, 0).unwrap_err();
        assert!(matches!(err, AcpError::BadSignature), "got {err:?}");
    }

    /// A V2-era signature (domain version "1") must not verify as an ACP.
    /// This is the cutover made explicit: there is no overlap window.
    #[test]
    fn v2_domain_signature_rejected() {
        let s = signer();
        let mut acp = signed_global_acp(&s, u64::MAX);
        let issuer = s.address();
        let payload = ACPIssuerSelf {
            issuer,
            expiration: u64::MAX,
            recipient: Address::ZERO,
            revokerData: U256::ZERO,
            revokerContract: Address::ZERO,
            scope: SCOPE_GLOBAL,
            contracts: vec![],
            handles: vec![],
            sealingKey: FixedBytes::ZERO,
        };
        let v2_domain = eip712_domain! {
            name: "ACL",
            version: "1",
            chain_id: TEST_CHAIN_ID,
            verifying_contract: TEST_TM_ADDR,
        };
        acp.issuer_signature = s
            .sign_hash_sync(&payload.eip712_signing_hash(&v2_domain))
            .expect("sign")
            .as_bytes()
            .to_vec();
        let err = verify_local(&acp, TEST_CHAIN_ID, TEST_TM_ADDR, 0).unwrap_err();
        assert!(matches!(err, AcpError::BadSignature), "got {err:?}");
    }

    #[test]
    fn expired_acp_rejected() {
        let s = signer();
        let acp = signed_global_acp(&s, 100);
        // now > expiration
        let err = verify_local(&acp, TEST_CHAIN_ID, TEST_TM_ADDR, 200).unwrap_err();
        assert!(matches!(err, AcpError::Expired), "got {err:?}");
    }

    #[test]
    fn tampered_signature_rejected() {
        let s = signer();
        let mut acp = signed_global_acp(&s, u64::MAX);
        // Flip a bit in the signature.
        acp.issuer_signature[5] ^= 0x01;
        let err = verify_local(&acp, TEST_CHAIN_ID, TEST_TM_ADDR, 0).unwrap_err();
        assert!(matches!(err, AcpError::BadSignature), "got {err:?}");
    }

    #[test]
    fn signer_mismatch_rejected() {
        let s = signer();
        let mut acp = signed_global_acp(&s, u64::MAX);
        // Swap the declared issuer to a different (well-formed) address — the
        // signature is now valid for the original signer but doesn't match.
        acp.issuer = "0x000000000000000000000000000000000000beef".into();
        let err = verify_local(&acp, TEST_CHAIN_ID, TEST_TM_ADDR, 0).unwrap_err();
        assert!(matches!(err, AcpError::BadSignature), "got {err:?}");
    }

    #[test]
    fn wrong_chain_id_invalidates_signature() {
        let s = signer();
        let acp = signed_global_acp(&s, u64::MAX);
        // Same ACP, verify under a different chain → domain separator
        // mismatches → signature recovers to a different address than issuer.
        let err = verify_local(&acp, TEST_CHAIN_ID + 1, TEST_TM_ADDR, 0).unwrap_err();
        assert!(matches!(err, AcpError::BadSignature), "got {err:?}");
    }

    #[test]
    fn malformed_address_rejected() {
        let s = signer();
        let mut acp = signed_global_acp(&s, u64::MAX);
        acp.issuer = "not-an-address".into();
        let err = verify_local(&acp, TEST_CHAIN_ID, TEST_TM_ADDR, 0).unwrap_err();
        assert!(matches!(err, AcpError::Malformed(_)), "got {err:?}");
    }

    #[test]
    fn malformed_scope_entry_rejected() {
        let s = signer();
        let mut acp = signed_global_acp(&s, u64::MAX);
        acp.contracts = vec!["not-an-address".into()];
        let err = verify_local(&acp, TEST_CHAIN_ID, TEST_TM_ADDR, 0).unwrap_err();
        assert!(matches!(err, AcpError::Malformed(_)), "got {err:?}");
    }

    /// Oversized scope arrays are refused before we build an eth_call payload.
    #[test]
    fn oversized_scope_arrays_rejected() {
        let s = signer();
        let mut acp = signed_global_acp(&s, u64::MAX);
        acp.handles = vec![format!("{:#x}", FixedBytes::<32>::ZERO); MAX_SCOPE_ENTRIES + 1];
        let err = ACP::try_from(&acp).unwrap_err();
        assert!(matches!(err, AcpError::Malformed(_)), "got {err:?}");

        let mut acp = signed_global_acp(&s, u64::MAX);
        acp.contracts = vec![format!("{:#x}", Address::ZERO); MAX_SCOPE_ENTRIES + 1];
        let err = ACP::try_from(&acp).unwrap_err();
        assert!(matches!(err, AcpError::Malformed(_)), "got {err:?}");
    }

    #[test]
    fn malformed_signature_rejected_as_wrong_length() {
        let s = signer();
        let mut acp = signed_global_acp(&s, u64::MAX);
        // Truncate to 3 bytes — alloy's Signature::try_from will reject this.
        acp.issuer_signature = vec![0xde, 0xad, 0xbe];
        let err = verify_local(&acp, TEST_CHAIN_ID, TEST_TM_ADDR, 0).unwrap_err();
        assert!(matches!(err, AcpError::Malformed(_)), "got {err:?}");
    }

    // ---- provider reuse ---------------------------------------------------

    use std::sync::atomic::{AtomicUsize, Ordering};
    use std::sync::Arc;
    use tokio::io::{AsyncReadExt, AsyncWriteExt};
    use tokio::net::TcpListener;

    /// Minimal JSON-RPC mock that (a) counts how many TCP connections it
    /// accepts and (b) answers every `eth_call` with an ABI-encoded `true`
    /// over a keep-alive HTTP/1.1 connection. One connection serving N requests
    /// is exactly what connection reuse looks like on the wire; a fresh provider
    /// per call would instead open N connections. Returns `(url, conn_counter)`.
    async fn spawn_true_rpc() -> (String, Arc<AtomicUsize>) {
        let listener = TcpListener::bind("127.0.0.1:0").await.expect("bind");
        let url = format!("http://{}", listener.local_addr().unwrap());
        let conns = Arc::new(AtomicUsize::new(0));
        let conns_srv = conns.clone();

        tokio::spawn(async move {
            loop {
                let (mut sock, _) = match listener.accept().await {
                    Ok(p) => p,
                    Err(_) => return,
                };
                conns_srv.fetch_add(1, Ordering::SeqCst);
                tokio::spawn(async move {
                    let mut buf = [0u8; 4096];
                    // Serve multiple keep-alive requests on the same connection.
                    loop {
                        let n = match sock.read(&mut buf).await {
                            Ok(0) | Err(_) => return,
                            Ok(n) => n,
                        };
                        // Find the JSON-RPC id so the response correlates.
                        let body = &buf[..n];
                        let text = String::from_utf8_lossy(body);
                        let id = text
                            .split("\"id\":")
                            .nth(1)
                            .and_then(|s| s.split([',', '}']).next())
                            .map(|s| s.trim())
                            .filter(|s| !s.is_empty())
                            .unwrap_or("1")
                            .to_string();
                        // 32-byte ABI-encoded bool `true` (0x00..01).
                        let result = "0x".to_string() + &"00".repeat(31) + "01";
                        let json =
                            format!("{{\"jsonrpc\":\"2.0\",\"id\":{id},\"result\":\"{result}\"}}");
                        let resp = format!(
                            "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\
                             Content-Length: {}\r\nConnection: keep-alive\r\n\r\n{}",
                            json.len(),
                            json
                        );
                        if sock.write_all(resp.as_bytes()).await.is_err() {
                            return;
                        }
                    }
                });
            }
        });
        (url, conns)
    }

    /// A bad rpc_url must fail when the [`ChainConfig`] is built (boot), not
    /// lazily on the first verify call — this is what guarantees the provider
    /// exists pre-built and is reused rather than constructed per request.
    #[test]
    fn bad_rpc_url_fails_at_construction() {
        let err =
            ChainConfig::new("not a url".into(), TEST_TM_ADDR, Duration::from_secs(5)).unwrap_err();
        assert!(matches!(err, AcpError::Misconfigured(_)), "got {err:?}");
    }

    /// The provider is built once at construction and reused across calls:
    /// three sequential `verify_publicly_allowed` calls against one mock RPC
    /// all succeed AND the server accepts exactly **one** TCP connection. With
    /// the old per-call `ProviderBuilder::new().connect_http()` each call would
    /// open its own pool → three cold connections.
    #[tokio::test]
    async fn provider_reused_across_repeated_calls() {
        let (url, conns) = spawn_true_rpc().await;

        let cfg =
            ChainConfig::new(url, TEST_TM_ADDR, Duration::from_secs(5)).expect("valid rpc_url");
        let chains = ChainsVerifierConfig {
            chains: HashMap::from([(TEST_CHAIN_ID, cfg)]),
        };

        let handle = U256::from(1u8);
        for i in 0..3 {
            verify_publicly_allowed(&chains, handle, TEST_CHAIN_ID)
                .await
                .unwrap_or_else(|e| panic!("call {i} should succeed, got {e:?}"));
        }

        assert_eq!(
            conns.load(Ordering::SeqCst),
            1,
            "expected the pooled provider to reuse one connection across 3 calls"
        );
    }
}
